services:
  redis-service:
    image: "redis:latest"
    hostname: redis
    ports:
      - "6379:6379"
  java-service:
    image: movie-db
    command: java -jar -Dspring.profiles.active=develop /movie-db.jar
    environment:
        - OMDBKEY=${OMDBKEY}
    ports:
      - "8080:8080"
    links:
      - redis-server